include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    mixin_inherits_from_not_object: ignore

linter:
  rules:
    library_private_types_in_public_api: false
    constant_identifier_names: false
    library_prefixes: false